const productos = [
  {
    id: 1,
    categoria: "Pantalones",
    nombre: "Baggie azul",
    estadoStock: "Últimas unidades",
    precio: 15000,
    imagen: "img/producto-1.webp",
    descuento: "-15% OFF",
    claseStock: "text-danger",
  },
  {
    id: 2,
    categoria: "Remeras",
    nombre: "Remera regular fit",
    estadoStock: "Stock alto",
    precio: 8000,
    imagen: "img/producto-2.webp",
    descuento: "-20% OFF",
    claseStock: "text-success",
  },
  {
    id: 3,
    categoria: "Camperas",
    nombre: "Campera Jean Hombre",
    estadoStock: "Stock medio",
    precio: 25000,
    imagen: "img/producto-3.webp",
    descuento: "-10% OFF",
    claseStock: "text-warning",
  },
  {
    id: 4,
    categoria: "Buzos",
    nombre: "Buzo Hoodie",
    estadoStock: "Últimas unidades",
    precio: 18000,
    imagen: "img/producto-4.webp",
    descuento: "-25% OFF",
    claseStock: "text-danger",
  },
  {
    id: 5,
    categoria: "Combos",
    nombre: "Conjunto 1",
    estadoStock: "Stock alto",
    precio: 35000,
    imagen: "img/producto-5.webp",
    descuento: "-30% OFF",
    claseStock: "text-success",
  },
  {
    id: 6,
    categoria: "Accesorios",
    nombre: "Bag Negra",
    estadoStock: "Stock medio",
    precio: 5000,
    imagen: "img/producto-6.jpg",
    descuento: "-15% OFF",
    claseStock: "text-warning",
  },
  {
    id: 7,
    categoria: "Pantalones",
    nombre: "Baggie azul claro",
    estadoStock: "Stock alto",
    precio: 15000,
    imagen: "img/producto-7.webp",
    descuento: "-20% OFF",
    claseStock: "text-success",
  },
  {
    id: 8,
    categoria: "Remeras",
    nombre: "Remera Relaxed",
    estadoStock: "Últimas unidades",
    precio: 8500,
    imagen: "img/producto-8.webp",
    descuento: "-10% OFF",
    claseStock: "text-danger",
  },
  {
    id: 9,
    categoria: "Camperas",
    nombre: "Campera Jean Mujer",
    estadoStock: "Stock medio",
    precio: 24000,
    imagen: "img/producto-9.webp",
    descuento: "-25% OFF",
    claseStock: "text-warning",
  },
  {
    id: 10,
    categoria: "Buzos",
    nombre: "Buzo Hoodie",
    estadoStock: "Stock alto",
    precio: 18500,
    imagen: "img/producto-10.webp",
    descuento: "-30% OFF",
    claseStock: "text-success",
  },
  {
    id: 11,
    categoria: "Combos",
    nombre: "Conjunto 2",
    estadoStock: "Últimas unidades",
    precio: 32000,
    imagen: "img/producto-11.jpg",
    descuento: "-15% OFF",
    claseStock: "text-danger",
  },
  {
    id: 12,
    categoria: "Accesorios",
    nombre: "Mini bag Negra",
    estadoStock: "Stock medio",
    precio: 4500,
    imagen: "img/producto-12.jpg",
    descuento: "-20% OFF",
    claseStock: "text-warning",
  },
  {
    id: 13,
    categoria: "Pantalones",
    nombre: "Baggie azul oscuro",
    estadoStock: "Stock alto",
    precio: 15500,
    imagen: "img/producto-13.webp",
    descuento: "-10% OFF",
    claseStock: "text-success",
  },
  {
    id: 14,
    categoria: "Remeras",
    nombre: "Remera Boxy fit",
    estadoStock: "Últimas unidades",
    precio: 9000,
    imagen: "img/producto-14.webp",
    descuento: "-25% OFF",
    claseStock: "text-danger",
  },
  {
    id: 15,
    categoria: "Camperas",
    nombre: "Campera Abrigo",
    estadoStock: "Stock medio",
    precio: 45000,
    imagen: "img/producto-15.jpg",
    descuento: "-30% OFF",
    claseStock: "text-warning",
  },
  {
    id: 16,
    categoria: "Buzos",
    nombre: "Buzo Hoodie",
    estadoStock: "Stock alto",
    precio: 19000,
    imagen: "img/producto-16.webp",
    descuento: "-15% OFF",
    claseStock: "text-success",
  },
  {
    id: 17,
    categoria: "Combos",
    nombre: "Conjunto 3",
    estadoStock: "Últimas unidades",
    precio: 38000,
    imagen: "img/producto-17.webp",
    descuento: "-20% OFF",
    claseStock: "text-danger",
  },
  {
    id: 18,
    categoria: "Accesorios",
    nombre: "Mini bag mostaza",
    estadoStock: "Stock alto",
    precio: 4800,
    imagen: "img/producto-18.jpg",
    descuento: "-10% OFF",
    claseStock: "text-success",
  },
  {
    id: 19,
    categoria: "Pantalones",
    nombre: "Baggie Negro",
    estadoStock: "Stock medio",
    precio: 16000,
    imagen: "img/producto-19.webp",
    descuento: "-25% OFF",
    claseStock: "text-warning",
  },
  {
    id: 20,
    categoria: "Remeras",
    nombre: "Remera Classic",
    estadoStock: "Últimas unidades",
    precio: 7500,
    imagen: "img/producto-20.webp",
    descuento: "-30% OFF",
    claseStock: "text-danger",
  },
  {
    id: 21,
    categoria: "Camperas",
    nombre: "Campera Softshell",
    estadoStock: "Stock alto",
    precio: 32000,
    imagen: "img/producto-21.webp",
    descuento: "-15% OFF",
    claseStock: "text-success",
  },
  {
    id: 22,
    categoria: "Buzos",
    nombre: "Buzo Hoodie",
    estadoStock: "Stock medio",
    precio: 20000,
    imagen: "img/producto-22.webp",
    descuento: "-20% OFF",
    claseStock: "text-warning",
  },
  {
    id: 23,
    categoria: "Combos",
    nombre: "Conjunto Deportivo",
    estadoStock: "Stock alto",
    precio: 28000,
    imagen: "img/producto-23.webp",
    descuento: "-10% OFF",
    claseStock: "text-success",
  },
  {
    id: 24,
    categoria: "Accesorios",
    nombre: "Bag Gris",
    estadoStock: "Últimas unidades",
    precio: 5500,
    imagen: "img/producto-24.jpg",
    descuento: "-25% OFF",
    claseStock: "text-danger",
  },
];

function inicializarProductos() {
  if (!localStorage.getItem("productos")) {
    localStorage.setItem("productos", JSON.stringify(productos));
    console.log("Productos cargados en LocalStorage por primera vez.");
  }
}

inicializarProductos();
